#####################################################
# Cours :             LOG120
# Session :           Saison automne 2009
# Groupe :            03
# Projet :            Laboratoire #1
# Étudiant(e)(s) :    Gabriel Desmarais
# Code(s) perm. :     DESG24078908
# Professeur :        Jocelyn Benoît
# Chargé de labo.:    Vincent Carrier
# 					  Yanick Rochon
# Nom du fichier :	  MAKEFILE					 
# Date créée :        2009-09-29
# Date dern. modif. : 2009-09-29
######################################################
# Historique des modifications
######################################################
# aaaa-mm-jj         Version initiale
######################################################

all: Main.class

Carte.class: src\cartes\Carte.java 
 	javac -cp bin src\cartes\Carte.java -d bin\cartes
 	
ComparateurCartesInverse.class: src\cartes\ComparateurCartesInverse.java 
 	javac -cp bin src\cartes\ComparateurCartesInverse.java -d bin\cartes
 	
CouleurCarte.class: src\cartes\CouleurCarte.java 
 	javac -cp bin src\cartes\CouleurCarte.java -d bin\cartes
 	
Denomination.class: src\cartes\Denomination.java 
 	javac -cp bin src\cartes\Denomination.java -d bin\cartes
 	
AbstractAnalyseurRang.class: src\mains\AbstractAnalyseurRang.java 
 	javac -cp bin src\mains\AbstractAnalyseurRang.java -d bin\mains

Main.class: src\mains\Main.java 
 	javac -cp bin src\mains\Main.java -d bin\mains

RangPoker.class: src\mains\RangPoker.java 
 	javac -cp bin src\mains\RangPoker.java -d bin\mains

ReqAnalyseMain.class: src\mains\ReqAnalyseMain.java 
 	javac -cp bin src\mains\ReqAnalyseMain.java -d bin\mains

Brelan.class: src\mains\Rang\Brelan.java 
 	javac -cp bin src\mains\Rang\Brelan.java -d bin\mains\Rang

Carre.class: src\mains\Rang\Carre.java 
 	javac -cp bin src\mains\Rang\Carre.java -d bin\mains\Rang

CarteSuperieure.class: src\mains\Rang\CarteSuperieure.java 
 	javac -cp bin src\mains\Rang\CarteSuperieure.java -d bin\mains\Rang

Couleur.class: src\mains\Rang\Couleur.java 
 	javac -cp bin src\mains\Rang\Couleur.java -d bin\mains\Rang

DeuxPaires.class: src\mains\Rang\DeuxPaires.java 
 	javac -cp bin src\mains\Rang\DeuxPaires.java -d bin\mains\Rang

MainPleine.class: src\mains\Rang\MainPleine.java 
 	javac -cp bin src\mains\Rang\MainPleine.java -d bin\mains\Rang

Paire.class: src\mains\Rang\Paire.java 
 	javac -cp bin src\mains\Rang\Paire.java -d bin\mains\Rang

Quinte.class: src\mains\Rang\Quinte.java 
 	javac -cp bin src\mains\Rang\Quinte.java -d bin\mains\Rang

QuinteCouleur.class: src\mains\Rang\QuinteCouleur.java 
 	javac -cp bin src\mains\Rang\QuinteCouleur.java -d bin\mains\Rang

QuinteRoyale.class: src\mains\Rang\QuinteRoyale.java 
 	javac -cp bin src\mains\Rang\QuinteRoyale.java -d bin\mains\Rang

Quintuplet.class: src\mains\Rang\Quintuplet.java 
 	javac -cp bin src\mains\Rang\Quintuplet.java -d bin\mains\Rang

clean:
 	del bin\*.class
